### ISSUE TITLE
How can I get the dataset TAC2011.

### ISSUE THREAD

**Issue by RichardWang11** [oriern/ProCluster#3]
I dont know how to download the dataset, please give me some information, thanks.

**Comment by oriern** [comment]
Hi,
Theoretically, you can download all DUC and TAC datasets from their NIST websites (TAC2011- https://tac.nist.gov/data/past/2011/Summ11.html) after signing some agreements. Indeed, it looks like specifically  TAC2011 documents are not published directly anymore, but can be extracted from Gigawords.
Unfortunately, as our lab signed their agreement, I am not allowed to publish this dataset.

**Comment by oriern** [comment]
Closing issue
