### ISSUE TITLE
About the fine-tuned CDLM

### ISSUE THREAD

**Issue by kevinyhl** [oriern/ProCluster#4]
Hi, may you provide the fine-tuned CDLM? thanks

**Comment by oriern** [comment]
Hi,
All trained models (including two CDLM models - one for DUC2004 and one for TAC2011) are in [here](https://drive.google.com/file/d/1CNaTH1k5oflmGiljQ7JL6NQ_3uz5tdvq/view).

**Comment by kevinyhl** [comment]
Thank you very much!
